/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/

// AUTOGENERATED WITH `yarn extract`, DO NOT EDIT MANUALLY

import { ColorDefaults } from './colorValue';

export type ColorIdentifier =
  | 'foreground'
  | 'errorForeground'
  | 'descriptionForeground'
  | 'icon.foreground'
  | 'focusBorder'
  | 'contrastBorder'
  | 'contrastActiveBorder'
  | 'selection.background'
  | 'textSeparator.foreground'
  | 'textLink.foreground'
  | 'textLink.activeForeground'
  | 'textPreformat.foreground'
  | 'textBlockQuote.background'
  | 'textBlockQuote.border'
  | 'textCodeBlock.background'
  | 'widget.shadow'
  | 'input.background'
  | 'input.foreground'
  | 'input.border'
  | 'inputOption.activeBorder'
  | 'inputOption.activeBackground'
  | 'inputOption.activeForeground'
  | 'input.placeholderForeground'
  | 'inputValidation.infoBackground'
  | 'inputValidation.infoForeground'
  | 'inputValidation.infoBorder'
  | 'inputValidation.warningBackground'
  | 'inputValidation.warningForeground'
  | 'inputValidation.warningBorder'
  | 'inputValidation.errorBackground'
  | 'inputValidation.errorForeground'
  | 'inputValidation.errorBorder'
  | 'dropdown.background'
  | 'dropdown.listBackground'
  | 'dropdown.foreground'
  | 'dropdown.border'
  | 'checkbox.background'
  | 'checkbox.foreground'
  | 'checkbox.border'
  | 'button.foreground'
  | 'button.background'
  | 'button.hoverBackground'
  | 'button.border'
  | 'button.secondaryForeground'
  | 'button.secondaryBackground'
  | 'button.secondaryHoverBackground'
  | 'badge.background'
  | 'badge.foreground'
  | 'scrollbar.shadow'
  | 'scrollbarSlider.background'
  | 'scrollbarSlider.hoverBackground'
  | 'scrollbarSlider.activeBackground'
  | 'progressBar.background'
  | 'editorError.background'
  | 'editorError.foreground'
  | 'editorError.border'
  | 'editorWarning.background'
  | 'editorWarning.foreground'
  | 'editorWarning.border'
  | 'editorInfo.background'
  | 'editorInfo.foreground'
  | 'editorInfo.border'
  | 'editorHint.foreground'
  | 'editorHint.border'
  | 'sash.hoverBorder'
  | 'editor.background'
  | 'editor.foreground'
  | 'editorWidget.background'
  | 'editorWidget.foreground'
  | 'editorWidget.border'
  | 'editorWidget.resizeBorder'
  | 'quickInput.background'
  | 'quickInput.foreground'
  | 'quickInputTitle.background'
  | 'pickerGroup.foreground'
  | 'pickerGroup.border'
  | 'keybindingLabel.background'
  | 'keybindingLabel.foreground'
  | 'keybindingLabel.border'
  | 'keybindingLabel.bottomBorder'
  | 'editor.selectionBackground'
  | 'editor.selectionForeground'
  | 'editor.inactiveSelectionBackground'
  | 'editor.selectionHighlightBackground'
  | 'editor.selectionHighlightBorder'
  | 'editor.findMatchBackground'
  | 'editor.findMatchHighlightBackground'
  | 'editor.findRangeHighlightBackground'
  | 'editor.findMatchBorder'
  | 'editor.findMatchHighlightBorder'
  | 'editor.findRangeHighlightBorder'
  | 'searchEditor.findMatchBackground'
  | 'searchEditor.findMatchBorder'
  | 'editor.hoverHighlightBackground'
  | 'editorHoverWidget.background'
  | 'editorHoverWidget.foreground'
  | 'editorHoverWidget.border'
  | 'editorHoverWidget.statusBarBackground'
  | 'editorLink.activeForeground'
  | 'editorInlayHint.foreground'
  | 'editorInlayHint.background'
  | 'editorLightBulb.foreground'
  | 'editorLightBulbAutoFix.foreground'
  | 'diffEditor.insertedTextBackground'
  | 'diffEditor.removedTextBackground'
  | 'diffEditor.insertedTextBorder'
  | 'diffEditor.removedTextBorder'
  | 'diffEditor.border'
  | 'diffEditor.diagonalFill'
  | 'list.focusBackground'
  | 'list.focusForeground'
  | 'list.focusOutline'
  | 'list.activeSelectionBackground'
  | 'list.activeSelectionForeground'
  | 'list.inactiveSelectionBackground'
  | 'list.inactiveSelectionForeground'
  | 'list.inactiveFocusBackground'
  | 'list.inactiveFocusOutline'
  | 'list.hoverBackground'
  | 'list.hoverForeground'
  | 'list.dropBackground'
  | 'list.highlightForeground'
  | 'list.focusHighlightForeground'
  | 'list.invalidItemForeground'
  | 'list.errorForeground'
  | 'list.warningForeground'
  | 'listFilterWidget.background'
  | 'listFilterWidget.outline'
  | 'listFilterWidget.noMatchesOutline'
  | 'list.filterMatchBackground'
  | 'list.filterMatchBorder'
  | 'tree.indentGuidesStroke'
  | 'tree.tableColumnsBorder'
  | 'list.deemphasizedForeground'
  /** @deprecated Please use quickInputList.focusBackground instead */
  | 'quickInput.list.focusBackground'
  | 'quickInputList.focusForeground'
  | 'quickInputList.focusBackground'
  | 'menu.border'
  | 'menu.foreground'
  | 'menu.background'
  | 'menu.selectionForeground'
  | 'menu.selectionBackground'
  | 'menu.selectionBorder'
  | 'menu.separatorBackground'
  | 'toolbar.hoverBackground'
  | 'toolbar.hoverOutline'
  | 'toolbar.activeBackground'
  | 'editor.snippetTabstopHighlightBackground'
  | 'editor.snippetTabstopHighlightBorder'
  | 'editor.snippetFinalTabstopHighlightBackground'
  | 'editor.snippetFinalTabstopHighlightBorder'
  | 'breadcrumb.foreground'
  | 'breadcrumb.background'
  | 'breadcrumb.focusForeground'
  | 'breadcrumb.activeSelectionForeground'
  | 'breadcrumbPicker.background'
  | 'merge.currentHeaderBackground'
  | 'merge.currentContentBackground'
  | 'merge.incomingHeaderBackground'
  | 'merge.incomingContentBackground'
  | 'merge.commonHeaderBackground'
  | 'merge.commonContentBackground'
  | 'merge.border'
  | 'editorOverviewRuler.currentContentForeground'
  | 'editorOverviewRuler.incomingContentForeground'
  | 'editorOverviewRuler.commonContentForeground'
  | 'editorOverviewRuler.findMatchForeground'
  | 'editorOverviewRuler.selectionHighlightForeground'
  | 'minimap.findMatchHighlight'
  | 'minimap.selectionHighlight'
  | 'minimap.errorHighlight'
  | 'minimap.warningHighlight'
  | 'minimap.background'
  | 'minimapSlider.background'
  | 'minimapSlider.hoverBackground'
  | 'minimapSlider.activeBackground'
  | 'problemsErrorIcon.foreground'
  | 'problemsWarningIcon.foreground'
  | 'problemsInfoIcon.foreground'
  | 'charts.foreground'
  | 'charts.lines'
  | 'charts.red'
  | 'charts.blue'
  | 'charts.yellow'
  | 'charts.orange'
  | 'charts.green'
  | 'charts.purple'
  | 'tab.activeBackground'
  | 'tab.unfocusedActiveBackground'
  | 'tab.inactiveBackground'
  | 'tab.unfocusedInactiveBackground'
  | 'tab.activeForeground'
  | 'tab.inactiveForeground'
  | 'tab.unfocusedActiveForeground'
  | 'tab.unfocusedInactiveForeground'
  | 'tab.hoverBackground'
  | 'tab.unfocusedHoverBackground'
  | 'tab.hoverForeground'
  | 'tab.unfocusedHoverForeground'
  | 'tab.border'
  | 'tab.lastPinnedBorder'
  | 'tab.activeBorder'
  | 'tab.unfocusedActiveBorder'
  | 'tab.activeBorderTop'
  | 'tab.unfocusedActiveBorderTop'
  | 'tab.hoverBorder'
  | 'tab.unfocusedHoverBorder'
  | 'tab.activeModifiedBorder'
  | 'tab.inactiveModifiedBorder'
  | 'tab.unfocusedActiveModifiedBorder'
  | 'tab.unfocusedInactiveModifiedBorder'
  | 'editorPane.background'
  /** @deprecated Deprecated: Background color of an editor group is no longer being supported with the introduction of the grid editor layout. You can use editorGroup.emptyBackground to set the background color of empty editor groups. */
  | 'editorGroup.background'
  | 'editorGroup.emptyBackground'
  | 'editorGroup.focusedEmptyBorder'
  | 'editorGroupHeader.tabsBackground'
  | 'editorGroupHeader.tabsBorder'
  | 'editorGroupHeader.noTabsBackground'
  | 'editorGroupHeader.border'
  | 'editorGroup.border'
  | 'editorGroup.dropBackground'
  | 'panel.background'
  | 'panel.border'
  | 'panelTitle.activeForeground'
  | 'panelTitle.inactiveForeground'
  | 'panelTitle.activeBorder'
  | 'panelInput.border'
  | 'panel.dropBorder'
  | 'panelSection.dropBackground'
  | 'panelSectionHeader.background'
  | 'panelSectionHeader.foreground'
  | 'panelSectionHeader.border'
  | 'panelSection.border'
  | 'banner.background'
  | 'banner.foreground'
  | 'banner.iconForeground'
  | 'statusBar.foreground'
  | 'statusBar.noFolderForeground'
  | 'statusBar.background'
  | 'statusBar.noFolderBackground'
  | 'statusBar.border'
  | 'statusBar.noFolderBorder'
  | 'statusBarItem.activeBackground'
  | 'statusBarItem.hoverBackground'
  | 'statusBarItem.prominentForeground'
  | 'statusBarItem.prominentBackground'
  | 'statusBarItem.prominentHoverBackground'
  | 'statusBarItem.errorBackground'
  | 'statusBarItem.errorForeground'
  | 'activityBar.background'
  | 'activityBar.foreground'
  | 'activityBar.inactiveForeground'
  | 'activityBar.border'
  | 'activityBar.activeBorder'
  | 'activityBar.activeFocusBorder'
  | 'activityBar.activeBackground'
  | 'activityBar.dropBorder'
  | 'activityBarBadge.background'
  | 'activityBarBadge.foreground'
  | 'statusBarItem.remoteBackground'
  | 'statusBarItem.remoteForeground'
  | 'extensionBadge.remoteBackground'
  | 'extensionBadge.remoteForeground'
  | 'sideBar.background'
  | 'sideBar.foreground'
  | 'sideBar.border'
  | 'sideBarTitle.foreground'
  | 'sideBar.dropBackground'
  | 'sideBarSectionHeader.background'
  | 'sideBarSectionHeader.foreground'
  | 'sideBarSectionHeader.border'
  | 'titleBar.activeForeground'
  | 'titleBar.inactiveForeground'
  | 'titleBar.activeBackground'
  | 'titleBar.inactiveBackground'
  | 'titleBar.border'
  | 'menubar.selectionForeground'
  | 'menubar.selectionBackground'
  | 'menubar.selectionBorder'
  | 'notificationCenter.border'
  | 'notificationToast.border'
  | 'notifications.foreground'
  | 'notifications.background'
  | 'notificationLink.foreground'
  | 'notificationCenterHeader.foreground'
  | 'notificationCenterHeader.background'
  | 'notifications.border'
  | 'notificationsErrorIcon.foreground'
  | 'notificationsWarningIcon.foreground'
  | 'notificationsInfoIcon.foreground'
  | 'window.activeBorder'
  | 'window.inactiveBorder'
  | 'terminal.background'
  | 'terminal.foreground'
  | 'terminalCursor.foreground'
  | 'terminalCursor.background'
  | 'terminal.selectionBackground'
  | 'terminal.border'
  | 'terminal.dropBackground'
  | 'editor.lineHighlightBackground'
  | 'editor.lineHighlightBorder'
  | 'editor.rangeHighlightBackground'
  | 'editor.rangeHighlightBorder'
  | 'editor.symbolHighlightBackground'
  | 'editor.symbolHighlightBorder'
  | 'editorCursor.foreground'
  | 'editorCursor.background'
  | 'editorWhitespace.foreground'
  | 'editorIndentGuide.background'
  | 'editorIndentGuide.activeBackground'
  | 'editorLineNumber.foreground'
  /** @deprecated Id is deprecated. Use 'editorLineNumber.activeForeground' instead. */
  | 'editorActiveLineNumber.foreground'
  | 'editorLineNumber.activeForeground'
  | 'editorRuler.foreground'
  | 'editorCodeLens.foreground'
  | 'editorBracketMatch.background'
  | 'editorBracketMatch.border'
  | 'editorOverviewRuler.border'
  | 'editorOverviewRuler.background'
  | 'editorGutter.background'
  | 'editorUnnecessaryCode.border'
  | 'editorUnnecessaryCode.opacity'
  | 'editorSuggestPreview.border'
  | 'editorSuggestPreview.opacity'
  | 'editorOverviewRuler.rangeHighlightForeground'
  | 'editorOverviewRuler.errorForeground'
  | 'editorOverviewRuler.warningForeground'
  | 'editorOverviewRuler.infoForeground'
  | 'editor.stackFrameHighlightBackground'
  | 'editor.focusedStackFrameHighlightBackground'
  | 'debugToolBar.background'
  | 'debugToolBar.border'
  | 'debugIcon.startForeground'
  | 'statusBar.debuggingBackground'
  | 'statusBar.debuggingForeground'
  | 'statusBar.debuggingBorder'
  | 'welcomePage.buttonBackground'
  | 'welcomePage.buttonHoverBackground'
  | 'welcomePage.background'
  | 'welcomePage.tileBackground'
  | 'welcomePage.tileHoverBackground'
  | 'welcomePage.tileShadow.'
  | 'welcomePage.progress.background'
  | 'welcomePage.progress.foreground'
  | 'symbolIcon.arrayForeground'
  | 'symbolIcon.booleanForeground'
  | 'symbolIcon.classForeground'
  | 'symbolIcon.colorForeground'
  | 'symbolIcon.constantForeground'
  | 'symbolIcon.constructorForeground'
  | 'symbolIcon.enumeratorForeground'
  | 'symbolIcon.enumeratorMemberForeground'
  | 'symbolIcon.eventForeground'
  | 'symbolIcon.fieldForeground'
  | 'symbolIcon.fileForeground'
  | 'symbolIcon.folderForeground'
  | 'symbolIcon.functionForeground'
  | 'symbolIcon.interfaceForeground'
  | 'symbolIcon.keyForeground'
  | 'symbolIcon.keywordForeground'
  | 'symbolIcon.methodForeground'
  | 'symbolIcon.moduleForeground'
  | 'symbolIcon.namespaceForeground'
  | 'symbolIcon.nullForeground'
  | 'symbolIcon.numberForeground'
  | 'symbolIcon.objectForeground'
  | 'symbolIcon.operatorForeground'
  | 'symbolIcon.packageForeground'
  | 'symbolIcon.propertyForeground'
  | 'symbolIcon.referenceForeground'
  | 'symbolIcon.snippetForeground'
  | 'symbolIcon.stringForeground'
  | 'symbolIcon.structForeground'
  | 'symbolIcon.textForeground'
  | 'symbolIcon.typeParameterForeground'
  | 'symbolIcon.unitForeground'
  | 'symbolIcon.variableForeground'
  | 'testing.iconFailed'
  | 'testing.iconErrored'
  | 'testing.iconPassed'
  | 'testing.runAction'
  | 'testing.iconQueued'
  | 'testing.iconUnset'
  | 'testing.iconSkipped'
  | 'testing.peekBorder'
  | 'testing.message.error.decorationForeground'
  | 'testing.message.error.lineBackground'
  | 'testing.message.warning.decorationForeground'
  | 'testing.message.warning.lineBackground'
  | 'testing.message.info.decorationForeground'
  | 'testing.message.info.lineBackground'
  | 'testing.message.hint.decorationForeground'
  | 'testing.message.hint.lineBackground'
  | 'editorOverviewRuler.bracketMatchForeground'
  | 'editor.linkedEditingBackground'
  | 'editor.wordHighlightBackground'
  | 'editor.wordHighlightStrongBackground'
  | 'editor.wordHighlightBorder'
  | 'editor.wordHighlightStrongBorder'
  | 'editorOverviewRuler.wordHighlightForeground'
  | 'editorOverviewRuler.wordHighlightStrongForeground'
  | 'editor.foldBackground'
  | 'editorGutter.foldingControlForeground'
  | 'editorGutter.commentRangeForeground'
  | 'debugExceptionWidget.border'
  | 'debugExceptionWidget.background'
  | 'extensionButton.prominentBackground'
  | 'extensionButton.prominentForeground'
  | 'extensionButton.prominentHoverBackground'
  | 'extensionIcon.starForeground'
  | 'ports.iconRunningProcessForeground'
  | 'settings.headerForeground'
  | 'settings.modifiedItemIndicator'
  | 'settings.dropdownBackground'
  | 'settings.dropdownForeground'
  | 'settings.dropdownBorder'
  | 'settings.dropdownListBorder'
  | 'settings.checkboxBackground'
  | 'settings.checkboxForeground'
  | 'settings.checkboxBorder'
  | 'settings.textInputBackground'
  | 'settings.textInputForeground'
  | 'settings.textInputBorder'
  | 'settings.numberInputBackground'
  | 'settings.numberInputForeground'
  | 'settings.numberInputBorder'
  | 'settings.focusedRowBackground'
  | 'notebook.rowHoverBackground'
  | 'notebook.focusedRowBorder'
  | 'peekViewTitle.background'
  | 'peekViewTitleLabel.foreground'
  | 'peekViewTitleDescription.foreground'
  | 'peekView.border'
  | 'peekViewResult.background'
  | 'peekViewResult.lineForeground'
  | 'peekViewResult.fileForeground'
  | 'peekViewResult.selectionBackground'
  | 'peekViewResult.selectionForeground'
  | 'peekViewEditor.background'
  | 'peekViewEditorGutter.background'
  | 'peekViewResult.matchHighlightBackground'
  | 'peekViewEditor.matchHighlightBackground'
  | 'peekViewEditor.matchHighlightBorder'
  | 'editorGutter.modifiedBackground'
  | 'editorGutter.addedBackground'
  | 'editorGutter.deletedBackground'
  | 'minimapGutter.modifiedBackground'
  | 'minimapGutter.addedBackground'
  | 'minimapGutter.deletedBackground'
  | 'editorOverviewRuler.modifiedForeground'
  | 'editorOverviewRuler.addedForeground'
  | 'editorOverviewRuler.deletedForeground'
  | 'editorMarkerNavigationError.background'
  | 'editorMarkerNavigationWarning.background'
  | 'editorMarkerNavigationInfo.background'
  | 'editorMarkerNavigation.background'
  | 'editorSuggestWidget.background'
  | 'editorSuggestWidget.border'
  | 'editorSuggestWidget.foreground'
  | 'editorSuggestWidget.selectedForeground'
  | 'editorSuggestWidget.selectedBackground'
  | 'editorSuggestWidget.highlightForeground'
  | 'editorSuggestWidget.focusHighlightForeground'
  | 'debugIcon.breakpointForeground'
  | 'debugIcon.breakpointDisabledForeground'
  | 'debugIcon.breakpointUnverifiedForeground'
  | 'debugIcon.breakpointCurrentStackframeForeground'
  | 'debugIcon.breakpointStackframeForeground'
  | 'editor.inlineValuesForeground'
  | 'editor.inlineValuesBackground'
  | 'debugTokenExpression.name'
  | 'debugTokenExpression.value'
  | 'debugTokenExpression.string'
  | 'debugTokenExpression.boolean'
  | 'debugTokenExpression.number'
  | 'debugTokenExpression.error'
  | 'debugView.exceptionLabelForeground'
  | 'debugView.exceptionLabelBackground'
  | 'debugView.stateLabelForeground'
  | 'debugView.stateLabelBackground'
  | 'debugView.valueChangedHighlight'
  | 'debugConsole.infoForeground'
  | 'debugConsole.warningForeground'
  | 'debugConsole.errorForeground'
  | 'debugConsole.sourceForeground'
  | 'debugConsoleInputIcon.foreground'
  | 'debugIcon.pauseForeground'
  | 'debugIcon.stopForeground'
  | 'debugIcon.disconnectForeground'
  | 'debugIcon.restartForeground'
  | 'debugIcon.stepOverForeground'
  | 'debugIcon.stepIntoForeground'
  | 'debugIcon.stepOutForeground'
  | 'debugIcon.continueForeground'
  | 'debugIcon.stepBackForeground'
  | 'walkThrough.embeddedEditorBackground'
  | 'scm.providerBorder'
  | 'searchEditor.textInputBorder'
  | 'notebook.cellBorderColor'
  | 'notebook.focusedEditorBorder'
  | 'notebookStatusSuccessIcon.foreground'
  | 'notebookStatusErrorIcon.foreground'
  | 'notebookStatusRunningIcon.foreground'
  | 'notebook.outputContainerBackgroundColor'
  | 'notebook.cellToolbarSeparator'
  | 'notebook.focusedCellBackground'
  | 'notebook.selectedCellBackground'
  | 'notebook.cellHoverBackground'
  | 'notebook.selectedCellBorder'
  | 'notebook.inactiveSelectedCellBorder'
  | 'notebook.focusedCellBorder'
  | 'notebook.inactiveFocusedCellBorder'
  | 'notebook.cellStatusBarItemHoverBackground'
  | 'notebook.cellInsertionIndicator'
  | 'notebookScrollbarSlider.background'
  | 'notebookScrollbarSlider.hoverBackground'
  | 'notebookScrollbarSlider.activeBackground'
  | 'notebook.symbolHighlightBackground'
  | 'notebook.cellEditorBackground'
  | 'terminal.ansiBlack'
  | 'terminal.ansiRed'
  | 'terminal.ansiGreen'
  | 'terminal.ansiYellow'
  | 'terminal.ansiBlue'
  | 'terminal.ansiMagenta'
  | 'terminal.ansiCyan'
  | 'terminal.ansiWhite'
  | 'terminal.ansiBrightBlack'
  | 'terminal.ansiBrightRed'
  | 'terminal.ansiBrightGreen'
  | 'terminal.ansiBrightYellow'
  | 'terminal.ansiBrightBlue'
  | 'terminal.ansiBrightMagenta'
  | 'terminal.ansiBrightCyan'
  | 'terminal.ansiBrightWhite';

export const colorDefaults = new Map<ColorIdentifier, ColorDefaults>([
  ['foreground', ['#616161', '#CCCCCC', '#FFFFFF']],
  ['errorForeground', ['#A1260D', '#F48771', '#F48771']],
  [
    'descriptionForeground',
    [
      '#717171',
      { op: 2, value: 'foreground', factor: 0.7 },
      { op: 2, value: 'foreground', factor: 0.7 },
    ],
  ],
  ['icon.foreground', ['#424242', '#C5C5C5', '#FFFFFF']],
  ['focusBorder', ['#0090F1', '#007FD4', '#F38518']],
  ['contrastBorder', [null, null, '#6FC3DF']],
  ['contrastActiveBorder', [null, null, 'focusBorder']],
  ['selection.background', [null, null, null]],
  ['textSeparator.foreground', ['#0000002e', '#ffffff2e', '#000000ff']],
  ['textLink.foreground', ['#006AB1', '#3794FF', '#3794FF']],
  ['textLink.activeForeground', ['#006AB1', '#3794FF', '#3794FF']],
  ['textPreformat.foreground', ['#A31515', '#D7BA7D', '#D7BA7D']],
  ['textBlockQuote.background', ['#7f7f7f1a', '#7f7f7f1a', null]],
  ['textBlockQuote.border', ['#007acc80', '#007acc80', '#ffffffff']],
  ['textCodeBlock.background', ['#dcdcdc66', '#0a0a0a66', '#000000ff']],
  [
    'widget.shadow',
    [
      { op: 2, value: '#000000ff', factor: 0.16 },
      { op: 2, value: '#000000ff', factor: 0.36 },
      null,
    ],
  ],
  ['input.background', ['#ffffffff', '#3C3C3C', '#000000ff']],
  ['input.foreground', ['foreground', 'foreground', 'foreground']],
  ['input.border', [null, null, 'contrastBorder']],
  ['inputOption.activeBorder', ['#007ACC00', '#007ACC00', 'contrastBorder']],
  [
    'inputOption.activeBackground',
    [
      { op: 2, value: 'focusBorder', factor: 0.2 },
      { op: 2, value: 'focusBorder', factor: 0.4 },
      '#00000000',
    ],
  ],
  ['inputOption.activeForeground', ['#000000ff', '#ffffffff', null]],
  [
    'input.placeholderForeground',
    [
      { op: 2, value: 'foreground', factor: 0.5 },
      { op: 2, value: 'foreground', factor: 0.5 },
      { op: 2, value: 'foreground', factor: 0.7 },
    ],
  ],
  ['inputValidation.infoBackground', ['#D6ECF2', '#063B49', '#000000ff']],
  ['inputValidation.infoForeground', [null, null, null]],
  ['inputValidation.infoBorder', ['#007acc', '#007acc', 'contrastBorder']],
  ['inputValidation.warningBackground', ['#F6F5D2', '#352A05', '#000000ff']],
  ['inputValidation.warningForeground', [null, null, null]],
  ['inputValidation.warningBorder', ['#B89500', '#B89500', 'contrastBorder']],
  ['inputValidation.errorBackground', ['#F2DEDE', '#5A1D1D', '#000000ff']],
  ['inputValidation.errorForeground', [null, null, null]],
  ['inputValidation.errorBorder', ['#BE1100', '#BE1100', 'contrastBorder']],
  ['dropdown.background', ['#ffffffff', '#3C3C3C', '#000000ff']],
  ['dropdown.listBackground', [null, null, '#000000ff']],
  ['dropdown.foreground', [null, '#F0F0F0', '#ffffffff']],
  ['dropdown.border', ['#CECECE', 'dropdown.background', 'contrastBorder']],
  ['checkbox.background', ['dropdown.background', 'dropdown.background', 'dropdown.background']],
  ['checkbox.foreground', ['dropdown.foreground', 'dropdown.foreground', 'dropdown.foreground']],
  ['checkbox.border', ['dropdown.border', 'dropdown.border', 'dropdown.border']],
  ['button.foreground', ['#ffffffff', '#ffffffff', '#ffffffff']],
  ['button.background', ['#007ACC', '#0E639C', null]],
  [
    'button.hoverBackground',
    [
      { op: 0, value: 'button.background', factor: 0.2 },
      { op: 1, value: 'button.background', factor: 0.2 },
      null,
    ],
  ],
  ['button.border', ['contrastBorder', 'contrastBorder', 'contrastBorder']],
  ['button.secondaryForeground', ['#ffffffff', '#ffffffff', '#ffffffff']],
  ['button.secondaryBackground', ['#5F6A79', '#3A3D41', null]],
  [
    'button.secondaryHoverBackground',
    [
      { op: 0, value: 'button.secondaryBackground', factor: 0.2 },
      { op: 1, value: 'button.secondaryBackground', factor: 0.2 },
      null,
    ],
  ],
  ['badge.background', ['#C4C4C4', '#4D4D4D', '#000000ff']],
  ['badge.foreground', ['#333', '#ffffffff', '#ffffffff']],
  ['scrollbar.shadow', ['#DDDDDD', '#000000', null]],
  [
    'scrollbarSlider.background',
    ['#64646466', '#79797966', { op: 2, value: 'contrastBorder', factor: 0.6 }],
  ],
  [
    'scrollbarSlider.hoverBackground',
    ['#646464b3', '#646464b3', { op: 2, value: 'contrastBorder', factor: 0.8 }],
  ],
  ['scrollbarSlider.activeBackground', ['#00000099', '#bfbfbf66', 'contrastBorder']],
  ['progressBar.background', ['#0e70c0ff', '#0e70c0ff', 'contrastBorder']],
  ['editorError.background', [null, null, null]],
  ['editorError.foreground', ['#E51400', '#F48771', null]],
  ['editorError.border', [null, null, '#e47777cc']],
  ['editorWarning.background', [null, null, null]],
  ['editorWarning.foreground', ['#BF8803', '#CCA700', null]],
  ['editorWarning.border', [null, null, '#ffcc00cc']],
  ['editorInfo.background', [null, null, null]],
  ['editorInfo.foreground', ['#75BEFF', '#75BEFF', null]],
  ['editorInfo.border', [null, null, '#75beffcc']],
  ['editorHint.foreground', ['#6c6c6c', '#eeeeeeb3', null]],
  ['editorHint.border', [null, null, '#eeeeeecc']],
  ['sash.hoverBorder', ['focusBorder', 'focusBorder', 'focusBorder']],
  ['editor.background', ['#fffffe', '#1E1E1E', '#000000ff']],
  ['editor.foreground', ['#333333', '#BBBBBB', '#ffffffff']],
  ['editorWidget.background', ['#F3F3F3', '#252526', '#0C141F']],
  ['editorWidget.foreground', ['foreground', 'foreground', 'foreground']],
  ['editorWidget.border', ['#C8C8C8', '#454545', 'contrastBorder']],
  ['editorWidget.resizeBorder', [null, null, null]],
  [
    'quickInput.background',
    ['editorWidget.background', 'editorWidget.background', 'editorWidget.background'],
  ],
  [
    'quickInput.foreground',
    ['editorWidget.foreground', 'editorWidget.foreground', 'editorWidget.foreground'],
  ],
  ['quickInputTitle.background', ['#0000000f', '#ffffff1b', '#000000']],
  ['pickerGroup.foreground', ['#0066BF', '#3794FF', '#ffffffff']],
  ['pickerGroup.border', ['#CCCEDB', '#3F3F46', '#ffffffff']],
  ['keybindingLabel.background', ['#dddddd66', '#8080802b', '#00000000']],
  ['keybindingLabel.foreground', ['#555555ff', '#ccccccff', '#ffffffff']],
  ['keybindingLabel.border', ['#cccccc66', '#33333399', '#6fc3dfff']],
  ['keybindingLabel.bottomBorder', ['#bbbbbb66', '#44444499', '#6fc3dfff']],
  ['editor.selectionBackground', ['#ADD6FF', '#264F78', '#f3f518']],
  ['editor.selectionForeground', [null, null, '#000000']],
  [
    'editor.inactiveSelectionBackground',
    [
      { op: 2, value: 'editor.selectionBackground', factor: 0.5 },
      { op: 2, value: 'editor.selectionBackground', factor: 0.5 },
      { op: 2, value: 'editor.selectionBackground', factor: 0.5 },
    ],
  ],
  [
    'editor.selectionHighlightBackground',
    [
      {
        op: 4,
        value: 'editor.selectionBackground',
        background: 'editor.background',
        factor: 0.3,
        transparency: 0.6,
      },
      {
        op: 4,
        value: 'editor.selectionBackground',
        background: 'editor.background',
        factor: 0.3,
        transparency: 0.6,
      },
      null,
    ],
  ],
  ['editor.selectionHighlightBorder', [null, null, 'contrastActiveBorder']],
  ['editor.findMatchBackground', ['#A8AC94', '#515C6A', null]],
  ['editor.findMatchHighlightBackground', ['#EA5C0055', '#EA5C0055', null]],
  ['editor.findRangeHighlightBackground', ['#b4b4b44d', '#3a3d4166', null]],
  ['editor.findMatchBorder', [null, null, 'contrastActiveBorder']],
  ['editor.findMatchHighlightBorder', [null, null, 'contrastActiveBorder']],
  [
    'editor.findRangeHighlightBorder',
    [null, null, { op: 2, value: 'contrastActiveBorder', factor: 0.4 }],
  ],
  [
    'searchEditor.findMatchBackground',
    [
      { op: 2, value: 'editor.findMatchHighlightBackground', factor: 0.66 },
      { op: 2, value: 'editor.findMatchHighlightBackground', factor: 0.66 },
      'editor.findMatchHighlightBackground',
    ],
  ],
  [
    'searchEditor.findMatchBorder',
    [
      { op: 2, value: 'editor.findMatchHighlightBorder', factor: 0.66 },
      { op: 2, value: 'editor.findMatchHighlightBorder', factor: 0.66 },
      'editor.findMatchHighlightBorder',
    ],
  ],
  ['editor.hoverHighlightBackground', ['#ADD6FF26', '#264f7840', '#ADD6FF26']],
  [
    'editorHoverWidget.background',
    ['editorWidget.background', 'editorWidget.background', 'editorWidget.background'],
  ],
  [
    'editorHoverWidget.foreground',
    ['editorWidget.foreground', 'editorWidget.foreground', 'editorWidget.foreground'],
  ],
  [
    'editorHoverWidget.border',
    ['editorWidget.border', 'editorWidget.border', 'editorWidget.border'],
  ],
  [
    'editorHoverWidget.statusBarBackground',
    [
      { op: 0, value: 'editorHoverWidget.background', factor: 0.05 },
      { op: 1, value: 'editorHoverWidget.background', factor: 0.2 },
      'editorWidget.background',
    ],
  ],
  ['editorLink.activeForeground', ['#0000ffff', '#4E94CE', '#00ffffff']],
  [
    'editorInlayHint.foreground',
    ['editorWidget.foreground', 'editorWidget.background', 'editorWidget.background'],
  ],
  [
    'editorInlayHint.background',
    ['editorWidget.background', 'editorWidget.foreground', 'editorWidget.foreground'],
  ],
  ['editorLightBulb.foreground', ['#DDB100', '#FFCC00', '#FFCC00']],
  ['editorLightBulbAutoFix.foreground', ['#007ACC', '#75BEFF', '#75BEFF']],
  ['diffEditor.insertedTextBackground', ['#9bb95533', '#9bb95533', null]],
  ['diffEditor.removedTextBackground', ['#ff000033', '#ff000033', null]],
  ['diffEditor.insertedTextBorder', [null, null, '#33ff2eff']],
  ['diffEditor.removedTextBorder', [null, null, '#FF008F']],
  ['diffEditor.border', [null, null, 'contrastBorder']],
  ['diffEditor.diagonalFill', ['#22222233', '#cccccc33', null]],
  ['list.focusBackground', [null, null, null]],
  ['list.focusForeground', [null, null, null]],
  ['list.focusOutline', ['focusBorder', 'focusBorder', 'contrastActiveBorder']],
  ['list.activeSelectionBackground', ['#0060C0', '#094771', null]],
  ['list.activeSelectionForeground', ['#ffffffff', '#ffffffff', null]],
  ['list.inactiveSelectionBackground', ['#E4E6F1', '#37373D', null]],
  ['list.inactiveSelectionForeground', [null, null, null]],
  ['list.inactiveFocusBackground', [null, null, null]],
  ['list.inactiveFocusOutline', [null, null, null]],
  ['list.hoverBackground', ['#F0F0F0', '#2A2D2E', null]],
  ['list.hoverForeground', [null, null, null]],
  ['list.dropBackground', ['#D6EBFF', '#062F4A', null]],
  ['list.highlightForeground', ['#0066BF', '#18A3FF', 'focusBorder']],
  [
    'list.focusHighlightForeground',
    ['list.highlightForeground', 'list.highlightForeground', 'list.highlightForeground'],
  ],
  ['list.invalidItemForeground', ['#B89500', '#B89500', '#B89500']],
  ['list.errorForeground', ['#B01011', '#F88070', null]],
  ['list.warningForeground', ['#855F00', '#CCA700', null]],
  ['listFilterWidget.background', ['#efc1ad', '#653723', '#000000ff']],
  ['listFilterWidget.outline', ['#00000000', '#00000000', '#f38518']],
  ['listFilterWidget.noMatchesOutline', ['#BE1100', '#BE1100', 'contrastBorder']],
  [
    'list.filterMatchBackground',
    ['editor.findMatchHighlightBackground', 'editor.findMatchHighlightBackground', null],
  ],
  [
    'list.filterMatchBorder',
    ['editor.findMatchHighlightBorder', 'editor.findMatchHighlightBorder', 'contrastBorder'],
  ],
  ['tree.indentGuidesStroke', ['#a9a9a9', '#585858', '#a9a9a9']],
  ['tree.tableColumnsBorder', ['#61616120', '#CCCCCC20', null]],
  ['list.deemphasizedForeground', ['#8E8E90', '#8C8C8C', '#A7A8A9']],
  ['quickInput.list.focusBackground', [null, null, null]],
  [
    'quickInputList.focusForeground',
    [
      'list.activeSelectionForeground',
      'list.activeSelectionForeground',
      'list.activeSelectionForeground',
    ],
  ],
  [
    'quickInputList.focusBackground',
    [
      {
        op: 3,
        values: ['quickInput.list.focusBackground', 'list.activeSelectionBackground', '#D6EBFF'],
      },
      {
        op: 3,
        values: ['quickInput.list.focusBackground', 'list.activeSelectionBackground', '#062F4A'],
      },
      null,
    ],
  ],
  ['menu.border', [null, null, 'contrastBorder']],
  ['menu.foreground', ['foreground', 'dropdown.foreground', 'dropdown.foreground']],
  ['menu.background', ['dropdown.background', 'dropdown.background', 'dropdown.background']],
  [
    'menu.selectionForeground',
    [
      'list.activeSelectionForeground',
      'list.activeSelectionForeground',
      'list.activeSelectionForeground',
    ],
  ],
  [
    'menu.selectionBackground',
    [
      'list.activeSelectionBackground',
      'list.activeSelectionBackground',
      'list.activeSelectionBackground',
    ],
  ],
  ['menu.selectionBorder', [null, null, 'contrastActiveBorder']],
  ['menu.separatorBackground', ['#888888', '#BBBBBB', 'contrastBorder']],
  ['toolbar.hoverBackground', ['#b8b8b850', '#5a5d5e50', null]],
  ['toolbar.hoverOutline', [null, null, 'contrastActiveBorder']],
  [
    'toolbar.activeBackground',
    [
      { op: 0, value: 'toolbar.hoverBackground', factor: 0.1 },
      { op: 1, value: 'toolbar.hoverBackground', factor: 0.1 },
      null,
    ],
  ],
  ['editor.snippetTabstopHighlightBackground', ['#0a326433', '#7c7c7c4d', '#7c7c7c4d']],
  ['editor.snippetTabstopHighlightBorder', [null, null, null]],
  ['editor.snippetFinalTabstopHighlightBackground', [null, null, null]],
  ['editor.snippetFinalTabstopHighlightBorder', ['#0a326480', '#525252', '#525252']],
  [
    'breadcrumb.foreground',
    [
      { op: 2, value: 'foreground', factor: 0.8 },
      { op: 2, value: 'foreground', factor: 0.8 },
      { op: 2, value: 'foreground', factor: 0.8 },
    ],
  ],
  ['breadcrumb.background', ['editor.background', 'editor.background', 'editor.background']],
  [
    'breadcrumb.focusForeground',
    [
      { op: 0, value: 'foreground', factor: 0.2 },
      { op: 1, value: 'foreground', factor: 0.1 },
      { op: 1, value: 'foreground', factor: 0.1 },
    ],
  ],
  [
    'breadcrumb.activeSelectionForeground',
    [
      { op: 0, value: 'foreground', factor: 0.2 },
      { op: 1, value: 'foreground', factor: 0.1 },
      { op: 1, value: 'foreground', factor: 0.1 },
    ],
  ],
  [
    'breadcrumbPicker.background',
    ['editorWidget.background', 'editorWidget.background', 'editorWidget.background'],
  ],
  ['merge.currentHeaderBackground', ['#40c8ae80', '#40c8ae80', null]],
  [
    'merge.currentContentBackground',
    [
      { op: 2, value: 'merge.currentHeaderBackground', factor: 0.4 },
      { op: 2, value: 'merge.currentHeaderBackground', factor: 0.4 },
      { op: 2, value: 'merge.currentHeaderBackground', factor: 0.4 },
    ],
  ],
  ['merge.incomingHeaderBackground', ['#40a6ff80', '#40a6ff80', null]],
  [
    'merge.incomingContentBackground',
    [
      { op: 2, value: 'merge.incomingHeaderBackground', factor: 0.4 },
      { op: 2, value: 'merge.incomingHeaderBackground', factor: 0.4 },
      { op: 2, value: 'merge.incomingHeaderBackground', factor: 0.4 },
    ],
  ],
  ['merge.commonHeaderBackground', ['#60606066', '#60606066', null]],
  [
    'merge.commonContentBackground',
    [
      { op: 2, value: 'merge.commonHeaderBackground', factor: 0.4 },
      { op: 2, value: 'merge.commonHeaderBackground', factor: 0.4 },
      { op: 2, value: 'merge.commonHeaderBackground', factor: 0.4 },
    ],
  ],
  ['merge.border', [null, null, '#C3DF6F']],
  [
    'editorOverviewRuler.currentContentForeground',
    [
      { op: 2, value: 'merge.currentHeaderBackground', factor: 1 },
      { op: 2, value: 'merge.currentHeaderBackground', factor: 1 },
      'merge.border',
    ],
  ],
  [
    'editorOverviewRuler.incomingContentForeground',
    [
      { op: 2, value: 'merge.incomingHeaderBackground', factor: 1 },
      { op: 2, value: 'merge.incomingHeaderBackground', factor: 1 },
      'merge.border',
    ],
  ],
  [
    'editorOverviewRuler.commonContentForeground',
    [
      { op: 2, value: 'merge.commonHeaderBackground', factor: 1 },
      { op: 2, value: 'merge.commonHeaderBackground', factor: 1 },
      'merge.border',
    ],
  ],
  ['editorOverviewRuler.findMatchForeground', ['#d186167e', '#d186167e', '#AB5A00']],
  ['editorOverviewRuler.selectionHighlightForeground', ['#A0A0A0CC', '#A0A0A0CC', '#A0A0A0CC']],
  ['minimap.findMatchHighlight', ['#d18616', '#d18616', '#AB5A00']],
  ['minimap.selectionHighlight', ['#ADD6FF', '#264F78', '#ffffff']],
  ['minimap.errorHighlight', ['#ff1212b3', '#ff1212b3', '#ff3232ff']],
  [
    'minimap.warningHighlight',
    ['editorWarning.foreground', 'editorWarning.foreground', 'editorWarning.border'],
  ],
  ['minimap.background', [null, null, null]],
  [
    'minimapSlider.background',
    [
      { op: 2, value: 'scrollbarSlider.background', factor: 0.5 },
      { op: 2, value: 'scrollbarSlider.background', factor: 0.5 },
      { op: 2, value: 'scrollbarSlider.background', factor: 0.5 },
    ],
  ],
  [
    'minimapSlider.hoverBackground',
    [
      { op: 2, value: 'scrollbarSlider.hoverBackground', factor: 0.5 },
      { op: 2, value: 'scrollbarSlider.hoverBackground', factor: 0.5 },
      { op: 2, value: 'scrollbarSlider.hoverBackground', factor: 0.5 },
    ],
  ],
  [
    'minimapSlider.activeBackground',
    [
      { op: 2, value: 'scrollbarSlider.activeBackground', factor: 0.5 },
      { op: 2, value: 'scrollbarSlider.activeBackground', factor: 0.5 },
      { op: 2, value: 'scrollbarSlider.activeBackground', factor: 0.5 },
    ],
  ],
  [
    'problemsErrorIcon.foreground',
    ['editorError.foreground', 'editorError.foreground', 'editorError.foreground'],
  ],
  [
    'problemsWarningIcon.foreground',
    ['editorWarning.foreground', 'editorWarning.foreground', 'editorWarning.foreground'],
  ],
  [
    'problemsInfoIcon.foreground',
    ['editorInfo.foreground', 'editorInfo.foreground', 'editorInfo.foreground'],
  ],
  ['charts.foreground', ['foreground', 'foreground', 'foreground']],
  [
    'charts.lines',
    [
      { op: 2, value: 'foreground', factor: 0.5 },
      { op: 2, value: 'foreground', factor: 0.5 },
      { op: 2, value: 'foreground', factor: 0.5 },
    ],
  ],
  ['charts.red', ['editorError.foreground', 'editorError.foreground', 'editorError.foreground']],
  ['charts.blue', ['editorInfo.foreground', 'editorInfo.foreground', 'editorInfo.foreground']],
  [
    'charts.yellow',
    ['editorWarning.foreground', 'editorWarning.foreground', 'editorWarning.foreground'],
  ],
  [
    'charts.orange',
    ['minimap.findMatchHighlight', 'minimap.findMatchHighlight', 'minimap.findMatchHighlight'],
  ],
  ['charts.green', ['#388A34', '#89D185', '#89D185']],
  ['charts.purple', ['#652D90', '#B180D7', '#B180D7']],
  ['tab.activeBackground', ['editor.background', 'editor.background', 'editor.background']],
  [
    'tab.unfocusedActiveBackground',
    ['tab.activeBackground', 'tab.activeBackground', 'tab.activeBackground'],
  ],
  ['tab.inactiveBackground', ['#ECECEC', '#2D2D2D', null]],
  [
    'tab.unfocusedInactiveBackground',
    ['tab.inactiveBackground', 'tab.inactiveBackground', 'tab.inactiveBackground'],
  ],
  ['tab.activeForeground', ['#333333', '#ffffffff', '#ffffffff']],
  [
    'tab.inactiveForeground',
    [
      { op: 2, value: 'tab.activeForeground', factor: 0.7 },
      { op: 2, value: 'tab.activeForeground', factor: 0.5 },
      '#ffffffff',
    ],
  ],
  [
    'tab.unfocusedActiveForeground',
    [
      { op: 2, value: 'tab.activeForeground', factor: 0.7 },
      { op: 2, value: 'tab.activeForeground', factor: 0.5 },
      '#ffffffff',
    ],
  ],
  [
    'tab.unfocusedInactiveForeground',
    [
      { op: 2, value: 'tab.inactiveForeground', factor: 0.5 },
      { op: 2, value: 'tab.inactiveForeground', factor: 0.5 },
      '#ffffffff',
    ],
  ],
  ['tab.hoverBackground', [null, null, null]],
  [
    'tab.unfocusedHoverBackground',
    [
      { op: 2, value: 'tab.hoverBackground', factor: 0.7 },
      { op: 2, value: 'tab.hoverBackground', factor: 0.5 },
      null,
    ],
  ],
  ['tab.hoverForeground', [null, null, null]],
  [
    'tab.unfocusedHoverForeground',
    [
      { op: 2, value: 'tab.hoverForeground', factor: 0.5 },
      { op: 2, value: 'tab.hoverForeground', factor: 0.5 },
      null,
    ],
  ],
  ['tab.border', ['#F3F3F3', '#252526', 'contrastBorder']],
  [
    'tab.lastPinnedBorder',
    ['tree.indentGuidesStroke', 'tree.indentGuidesStroke', 'contrastBorder'],
  ],
  ['tab.activeBorder', [null, null, null]],
  [
    'tab.unfocusedActiveBorder',
    [
      { op: 2, value: 'tab.activeBorder', factor: 0.7 },
      { op: 2, value: 'tab.activeBorder', factor: 0.5 },
      null,
    ],
  ],
  ['tab.activeBorderTop', [null, null, null]],
  [
    'tab.unfocusedActiveBorderTop',
    [
      { op: 2, value: 'tab.activeBorderTop', factor: 0.7 },
      { op: 2, value: 'tab.activeBorderTop', factor: 0.5 },
      null,
    ],
  ],
  ['tab.hoverBorder', [null, null, null]],
  [
    'tab.unfocusedHoverBorder',
    [
      { op: 2, value: 'tab.hoverBorder', factor: 0.7 },
      { op: 2, value: 'tab.hoverBorder', factor: 0.5 },
      null,
    ],
  ],
  ['tab.activeModifiedBorder', ['#33AAEE', '#3399CC', null]],
  [
    'tab.inactiveModifiedBorder',
    [
      { op: 2, value: 'tab.activeModifiedBorder', factor: 0.5 },
      { op: 2, value: 'tab.activeModifiedBorder', factor: 0.5 },
      '#ffffffff',
    ],
  ],
  [
    'tab.unfocusedActiveModifiedBorder',
    [
      { op: 2, value: 'tab.activeModifiedBorder', factor: 0.7 },
      { op: 2, value: 'tab.activeModifiedBorder', factor: 0.5 },
      '#ffffffff',
    ],
  ],
  [
    'tab.unfocusedInactiveModifiedBorder',
    [
      { op: 2, value: 'tab.inactiveModifiedBorder', factor: 0.5 },
      { op: 2, value: 'tab.inactiveModifiedBorder', factor: 0.5 },
      '#ffffffff',
    ],
  ],
  ['editorPane.background', ['editor.background', 'editor.background', 'editor.background']],
  ['editorGroup.background', [null, null, null]],
  ['editorGroup.emptyBackground', [null, null, null]],
  ['editorGroup.focusedEmptyBorder', [null, null, 'focusBorder']],
  ['editorGroupHeader.tabsBackground', ['#F3F3F3', '#252526', null]],
  ['editorGroupHeader.tabsBorder', [null, null, null]],
  [
    'editorGroupHeader.noTabsBackground',
    ['editor.background', 'editor.background', 'editor.background'],
  ],
  ['editorGroupHeader.border', [null, null, 'contrastBorder']],
  ['editorGroup.border', ['#E7E7E7', '#444444', 'contrastBorder']],
  ['editorGroup.dropBackground', ['#2677cb2e', '#53595d80', null]],
  ['panel.background', ['editor.background', 'editor.background', 'editor.background']],
  ['panel.border', ['#80808059', '#80808059', 'contrastBorder']],
  ['panelTitle.activeForeground', ['#424242', '#E7E7E7', '#ffffffff']],
  [
    'panelTitle.inactiveForeground',
    [
      { op: 2, value: 'panelTitle.activeForeground', factor: 0.75 },
      { op: 2, value: 'panelTitle.activeForeground', factor: 0.6 },
      '#ffffffff',
    ],
  ],
  [
    'panelTitle.activeBorder',
    ['panelTitle.activeForeground', 'panelTitle.activeForeground', 'contrastBorder'],
  ],
  ['panelInput.border', ['#ddddddff', null, null]],
  [
    'panel.dropBorder',
    ['panelTitle.activeForeground', 'panelTitle.activeForeground', 'panelTitle.activeForeground'],
  ],
  [
    'panelSection.dropBackground',
    ['editorGroup.dropBackground', 'editorGroup.dropBackground', 'editorGroup.dropBackground'],
  ],
  ['panelSectionHeader.background', ['#80808033', '#80808033', null]],
  ['panelSectionHeader.foreground', [null, null, null]],
  ['panelSectionHeader.border', ['contrastBorder', 'contrastBorder', 'contrastBorder']],
  ['panelSection.border', ['panel.border', 'panel.border', 'panel.border']],
  [
    'banner.background',
    [
      'list.activeSelectionBackground',
      'list.activeSelectionBackground',
      'list.activeSelectionBackground',
    ],
  ],
  [
    'banner.foreground',
    [
      'list.activeSelectionForeground',
      'list.activeSelectionForeground',
      'list.activeSelectionForeground',
    ],
  ],
  [
    'banner.iconForeground',
    ['editorInfo.foreground', 'editorInfo.foreground', 'editorInfo.foreground'],
  ],
  ['statusBar.foreground', ['#FFFFFF', '#FFFFFF', '#FFFFFF']],
  [
    'statusBar.noFolderForeground',
    ['statusBar.foreground', 'statusBar.foreground', 'statusBar.foreground'],
  ],
  ['statusBar.background', ['#007ACC', '#007ACC', null]],
  ['statusBar.noFolderBackground', ['#68217A', '#68217A', null]],
  ['statusBar.border', [null, null, 'contrastBorder']],
  ['statusBar.noFolderBorder', ['statusBar.border', 'statusBar.border', 'statusBar.border']],
  ['statusBarItem.activeBackground', ['#ffffff2e', '#ffffff2e', '#ffffff2e']],
  ['statusBarItem.hoverBackground', ['#ffffff1f', '#ffffff1f', '#ffffff1f']],
  [
    'statusBarItem.prominentForeground',
    ['statusBar.foreground', 'statusBar.foreground', 'statusBar.foreground'],
  ],
  ['statusBarItem.prominentBackground', ['#00000080', '#00000080', '#00000080']],
  ['statusBarItem.prominentHoverBackground', ['#0000004d', '#0000004d', '#0000004d']],
  [
    'statusBarItem.errorBackground',
    [
      { op: 0, value: 'errorForeground', factor: 0.4 },
      { op: 0, value: 'errorForeground', factor: 0.4 },
      null,
    ],
  ],
  ['statusBarItem.errorForeground', ['#ffffffff', '#ffffffff', '#ffffffff']],
  ['activityBar.background', ['#2C2C2C', '#333333', '#000000']],
  ['activityBar.foreground', ['#ffffffff', '#ffffffff', '#ffffffff']],
  [
    'activityBar.inactiveForeground',
    [
      { op: 2, value: 'activityBar.foreground', factor: 0.4 },
      { op: 2, value: 'activityBar.foreground', factor: 0.4 },
      '#ffffffff',
    ],
  ],
  ['activityBar.border', [null, null, 'contrastBorder']],
  ['activityBar.activeBorder', ['activityBar.foreground', 'activityBar.foreground', null]],
  ['activityBar.activeFocusBorder', [null, null, null]],
  ['activityBar.activeBackground', [null, null, null]],
  [
    'activityBar.dropBorder',
    ['activityBar.foreground', 'activityBar.foreground', 'activityBar.foreground'],
  ],
  ['activityBarBadge.background', ['#007ACC', '#007ACC', '#000000']],
  ['activityBarBadge.foreground', ['#ffffffff', '#ffffffff', '#ffffffff']],
  [
    'statusBarItem.remoteBackground',
    ['activityBarBadge.background', 'activityBarBadge.background', 'activityBarBadge.background'],
  ],
  [
    'statusBarItem.remoteForeground',
    ['activityBarBadge.foreground', 'activityBarBadge.foreground', 'activityBarBadge.foreground'],
  ],
  [
    'extensionBadge.remoteBackground',
    ['activityBarBadge.background', 'activityBarBadge.background', 'activityBarBadge.background'],
  ],
  [
    'extensionBadge.remoteForeground',
    ['activityBarBadge.foreground', 'activityBarBadge.foreground', 'activityBarBadge.foreground'],
  ],
  ['sideBar.background', ['#F3F3F3', '#252526', '#000000']],
  ['sideBar.foreground', [null, null, null]],
  ['sideBar.border', [null, null, 'contrastBorder']],
  ['sideBarTitle.foreground', ['sideBar.foreground', 'sideBar.foreground', 'sideBar.foreground']],
  [
    'sideBar.dropBackground',
    ['editorGroup.dropBackground', 'editorGroup.dropBackground', 'editorGroup.dropBackground'],
  ],
  ['sideBarSectionHeader.background', ['#80808033', '#80808033', null]],
  [
    'sideBarSectionHeader.foreground',
    ['sideBar.foreground', 'sideBar.foreground', 'sideBar.foreground'],
  ],
  ['sideBarSectionHeader.border', ['contrastBorder', 'contrastBorder', 'contrastBorder']],
  ['titleBar.activeForeground', ['#333333', '#CCCCCC', '#FFFFFF']],
  [
    'titleBar.inactiveForeground',
    [
      { op: 2, value: 'titleBar.activeForeground', factor: 0.6 },
      { op: 2, value: 'titleBar.activeForeground', factor: 0.6 },
      null,
    ],
  ],
  ['titleBar.activeBackground', ['#DDDDDD', '#3C3C3C', '#000000']],
  [
    'titleBar.inactiveBackground',
    [
      { op: 2, value: 'titleBar.activeBackground', factor: 0.6 },
      { op: 2, value: 'titleBar.activeBackground', factor: 0.6 },
      null,
    ],
  ],
  ['titleBar.border', [null, null, 'contrastBorder']],
  [
    'menubar.selectionForeground',
    ['titleBar.activeForeground', 'titleBar.activeForeground', 'titleBar.activeForeground'],
  ],
  [
    'menubar.selectionBackground',
    [{ op: 2, value: '#000000ff', factor: 0.1 }, { op: 2, value: '#ffffffff', factor: 0.1 }, null],
  ],
  ['menubar.selectionBorder', [null, null, 'contrastActiveBorder']],
  ['notificationCenter.border', [null, null, 'contrastBorder']],
  ['notificationToast.border', [null, null, 'contrastBorder']],
  [
    'notifications.foreground',
    ['editorWidget.foreground', 'editorWidget.foreground', 'editorWidget.foreground'],
  ],
  [
    'notifications.background',
    ['editorWidget.background', 'editorWidget.background', 'editorWidget.background'],
  ],
  [
    'notificationLink.foreground',
    ['textLink.foreground', 'textLink.foreground', 'textLink.foreground'],
  ],
  ['notificationCenterHeader.foreground', [null, null, null]],
  [
    'notificationCenterHeader.background',
    [
      { op: 0, value: 'notifications.background', factor: 0.05 },
      { op: 1, value: 'notifications.background', factor: 0.3 },
      'notifications.background',
    ],
  ],
  [
    'notifications.border',
    [
      'notificationCenterHeader.background',
      'notificationCenterHeader.background',
      'notificationCenterHeader.background',
    ],
  ],
  [
    'notificationsErrorIcon.foreground',
    ['editorError.foreground', 'editorError.foreground', 'editorError.foreground'],
  ],
  [
    'notificationsWarningIcon.foreground',
    ['editorWarning.foreground', 'editorWarning.foreground', 'editorWarning.foreground'],
  ],
  [
    'notificationsInfoIcon.foreground',
    ['editorInfo.foreground', 'editorInfo.foreground', 'editorInfo.foreground'],
  ],
  ['window.activeBorder', [null, null, 'contrastBorder']],
  ['window.inactiveBorder', [null, null, 'contrastBorder']],
  ['terminal.background', [null, null, null]],
  ['terminal.foreground', ['#333333', '#CCCCCC', '#FFFFFF']],
  ['terminalCursor.foreground', [null, null, null]],
  ['terminalCursor.background', [null, null, null]],
  ['terminal.selectionBackground', ['#00000040', '#FFFFFF40', '#FFFFFF80']],
  ['terminal.border', ['panel.border', 'panel.border', 'panel.border']],
  [
    'terminal.dropBackground',
    ['editorGroup.dropBackground', 'editorGroup.dropBackground', 'editorGroup.dropBackground'],
  ],
  ['editor.lineHighlightBackground', [null, null, null]],
  ['editor.lineHighlightBorder', ['#eeeeee', '#282828', '#f38518']],
  ['editor.rangeHighlightBackground', ['#fdff0033', '#ffffff0b', null]],
  ['editor.rangeHighlightBorder', [null, null, 'contrastActiveBorder']],
  [
    'editor.symbolHighlightBackground',
    ['editor.findMatchHighlightBackground', 'editor.findMatchHighlightBackground', null],
  ],
  ['editor.symbolHighlightBorder', [null, null, 'contrastActiveBorder']],
  ['editorCursor.foreground', ['#000000ff', '#AEAFAD', '#ffffffff']],
  ['editorCursor.background', [null, null, null]],
  ['editorWhitespace.foreground', ['#33333333', '#e3e4e229', '#e3e4e229']],
  [
    'editorIndentGuide.background',
    ['editorWhitespace.foreground', 'editorWhitespace.foreground', 'editorWhitespace.foreground'],
  ],
  [
    'editorIndentGuide.activeBackground',
    ['editorWhitespace.foreground', 'editorWhitespace.foreground', 'editorWhitespace.foreground'],
  ],
  ['editorLineNumber.foreground', ['#237893', '#858585', '#ffffffff']],
  ['editorActiveLineNumber.foreground', ['#0B216F', '#c6c6c6', 'contrastActiveBorder']],
  [
    'editorLineNumber.activeForeground',
    [
      'editorActiveLineNumber.foreground',
      'editorActiveLineNumber.foreground',
      'editorActiveLineNumber.foreground',
    ],
  ],
  ['editorRuler.foreground', ['#d3d3d3ff', '#5A5A5A', '#ffffffff']],
  ['editorCodeLens.foreground', ['#999999', '#999999', '#999999']],
  ['editorBracketMatch.background', ['#0064001a', '#0064001a', '#0064001a']],
  ['editorBracketMatch.border', ['#B9B9B9', '#888', 'contrastBorder']],
  ['editorOverviewRuler.border', ['#7f7f7f4d', '#7f7f7f4d', '#7f7f7f4d']],
  ['editorOverviewRuler.background', [null, null, null]],
  ['editorGutter.background', ['editor.background', 'editor.background', 'editor.background']],
  ['editorUnnecessaryCode.border', [null, null, '#ffffffcc']],
  ['editorUnnecessaryCode.opacity', ['#00000077', '#000000aa', null]],
  ['editorSuggestPreview.border', [null, null, '#ffffffcc']],
  ['editorSuggestPreview.opacity', ['#00000077', '#ffffffaa', null]],
  ['editorOverviewRuler.rangeHighlightForeground', ['#007acc99', '#007acc99', '#007acc99']],
  ['editorOverviewRuler.errorForeground', ['#ff1212b3', '#ff1212b3', '#ff3232ff']],
  [
    'editorOverviewRuler.warningForeground',
    ['editorWarning.foreground', 'editorWarning.foreground', 'editorWarning.border'],
  ],
  [
    'editorOverviewRuler.infoForeground',
    ['editorInfo.foreground', 'editorInfo.foreground', 'editorInfo.border'],
  ],
  ['editor.stackFrameHighlightBackground', ['#ffff6673', '#ffff0033', '#ffff0033']],
  ['editor.focusedStackFrameHighlightBackground', ['#cee7ce73', '#7abd7a4d', '#7abd7a4d']],
  ['debugToolBar.background', ['#F3F3F3', '#333333', '#000000']],
  ['debugToolBar.border', [null, null, null]],
  ['debugIcon.startForeground', ['#388A34', '#89D185', '#89D185']],
  ['statusBar.debuggingBackground', ['#CC6633', '#CC6633', '#CC6633']],
  [
    'statusBar.debuggingForeground',
    ['statusBar.foreground', 'statusBar.foreground', 'statusBar.foreground'],
  ],
  ['statusBar.debuggingBorder', ['statusBar.border', 'statusBar.border', 'statusBar.border']],
  ['welcomePage.buttonBackground', [null, null, null]],
  ['welcomePage.buttonHoverBackground', [null, null, null]],
  ['welcomePage.background', [null, null, null]],
  ['welcomePage.tileBackground', ['editorWidget.background', 'editorWidget.background', '#000']],
  [
    'welcomePage.tileHoverBackground',
    [
      { op: 0, value: 'editorWidget.background', factor: 0.1 },
      { op: 1, value: 'editorWidget.background', factor: 0.2 },
      null,
    ],
  ],
  ['welcomePage.tileShadow.', ['widget.shadow', 'widget.shadow', null]],
  ['welcomePage.progress.background', ['input.background', 'input.background', 'input.background']],
  [
    'welcomePage.progress.foreground',
    ['textLink.foreground', 'textLink.foreground', 'textLink.foreground'],
  ],
  ['symbolIcon.arrayForeground', ['foreground', 'foreground', 'foreground']],
  ['symbolIcon.booleanForeground', ['foreground', 'foreground', 'foreground']],
  ['symbolIcon.classForeground', ['#D67E00', '#EE9D28', '#EE9D28']],
  ['symbolIcon.colorForeground', ['foreground', 'foreground', 'foreground']],
  ['symbolIcon.constantForeground', ['foreground', 'foreground', 'foreground']],
  ['symbolIcon.constructorForeground', ['#652D90', '#B180D7', '#B180D7']],
  ['symbolIcon.enumeratorForeground', ['#D67E00', '#EE9D28', '#EE9D28']],
  ['symbolIcon.enumeratorMemberForeground', ['#007ACC', '#75BEFF', '#75BEFF']],
  ['symbolIcon.eventForeground', ['#D67E00', '#EE9D28', '#EE9D28']],
  ['symbolIcon.fieldForeground', ['#007ACC', '#75BEFF', '#75BEFF']],
  ['symbolIcon.fileForeground', ['foreground', 'foreground', 'foreground']],
  ['symbolIcon.folderForeground', ['foreground', 'foreground', 'foreground']],
  ['symbolIcon.functionForeground', ['#652D90', '#B180D7', '#B180D7']],
  ['symbolIcon.interfaceForeground', ['#007ACC', '#75BEFF', '#75BEFF']],
  ['symbolIcon.keyForeground', ['foreground', 'foreground', 'foreground']],
  ['symbolIcon.keywordForeground', ['foreground', 'foreground', 'foreground']],
  ['symbolIcon.methodForeground', ['#652D90', '#B180D7', '#B180D7']],
  ['symbolIcon.moduleForeground', ['foreground', 'foreground', 'foreground']],
  ['symbolIcon.namespaceForeground', ['foreground', 'foreground', 'foreground']],
  ['symbolIcon.nullForeground', ['foreground', 'foreground', 'foreground']],
  ['symbolIcon.numberForeground', ['foreground', 'foreground', 'foreground']],
  ['symbolIcon.objectForeground', ['foreground', 'foreground', 'foreground']],
  ['symbolIcon.operatorForeground', ['foreground', 'foreground', 'foreground']],
  ['symbolIcon.packageForeground', ['foreground', 'foreground', 'foreground']],
  ['symbolIcon.propertyForeground', ['foreground', 'foreground', 'foreground']],
  ['symbolIcon.referenceForeground', ['foreground', 'foreground', 'foreground']],
  ['symbolIcon.snippetForeground', ['foreground', 'foreground', 'foreground']],
  ['symbolIcon.stringForeground', ['foreground', 'foreground', 'foreground']],
  ['symbolIcon.structForeground', ['foreground', 'foreground', 'foreground']],
  ['symbolIcon.textForeground', ['foreground', 'foreground', 'foreground']],
  ['symbolIcon.typeParameterForeground', ['foreground', 'foreground', 'foreground']],
  ['symbolIcon.unitForeground', ['foreground', 'foreground', 'foreground']],
  ['symbolIcon.variableForeground', ['#007ACC', '#75BEFF', '#75BEFF']],
  ['testing.iconFailed', ['#f14c4c', '#f14c4c', '#000000']],
  ['testing.iconErrored', ['#f14c4c', '#f14c4c', '#000000']],
  ['testing.iconPassed', ['#73c991', '#73c991', '#000000']],
  ['testing.runAction', ['testing.iconPassed', 'testing.iconPassed', 'testing.iconPassed']],
  ['testing.iconQueued', ['#cca700', '#cca700', '#000000']],
  ['testing.iconUnset', ['#848484', '#848484', '#848484']],
  ['testing.iconSkipped', ['#848484', '#848484', '#848484']],
  [
    'testing.peekBorder',
    ['editorError.foreground', 'editorError.foreground', 'editorError.foreground'],
  ],
  [
    'testing.message.error.decorationForeground',
    ['editorError.foreground', 'editorError.foreground', 'editor.foreground'],
  ],
  ['testing.message.error.lineBackground', ['#ff000033', '#ff000033', null]],
  [
    'testing.message.warning.decorationForeground',
    ['editorWarning.foreground', 'editorWarning.foreground', 'editor.foreground'],
  ],
  ['testing.message.warning.lineBackground', ['#ffd00033', '#ffd00033', null]],
  [
    'testing.message.info.decorationForeground',
    ['editorInfo.foreground', 'editorInfo.foreground', 'editor.foreground'],
  ],
  ['testing.message.info.lineBackground', ['#007fff33', '#007fff33', null]],
  [
    'testing.message.hint.decorationForeground',
    ['editorHint.foreground', 'editorHint.foreground', 'editor.foreground'],
  ],
  ['testing.message.hint.lineBackground', [null, null, 'editor.foreground']],
  ['editorOverviewRuler.bracketMatchForeground', ['#A0A0A0', '#A0A0A0', '#A0A0A0']],
  ['editor.linkedEditingBackground', ['#ff00004d', '#ff00004d', '#ff00004d']],
  ['editor.wordHighlightBackground', ['#57575740', '#575757B8', null]],
  ['editor.wordHighlightStrongBackground', ['#0e639c40', '#004972B8', null]],
  ['editor.wordHighlightBorder', [null, null, 'contrastActiveBorder']],
  ['editor.wordHighlightStrongBorder', [null, null, 'contrastActiveBorder']],
  ['editorOverviewRuler.wordHighlightForeground', ['#A0A0A0CC', '#A0A0A0CC', '#A0A0A0CC']],
  ['editorOverviewRuler.wordHighlightStrongForeground', ['#C0A0C0CC', '#C0A0C0CC', '#C0A0C0CC']],
  [
    'editor.foldBackground',
    [
      { op: 2, value: 'editor.selectionBackground', factor: 0.3 },
      { op: 2, value: 'editor.selectionBackground', factor: 0.3 },
      null,
    ],
  ],
  [
    'editorGutter.foldingControlForeground',
    ['icon.foreground', 'icon.foreground', 'icon.foreground'],
  ],
  ['editorGutter.commentRangeForeground', ['#c5c5c5ff', '#c5c5c5ff', '#c5c5c5ff']],
  ['debugExceptionWidget.border', ['#a31515', '#a31515', '#a31515']],
  ['debugExceptionWidget.background', ['#f1dfde', '#420b0d', '#420b0d']],
  ['extensionButton.prominentBackground', ['button.background', 'button.background', null]],
  ['extensionButton.prominentForeground', ['button.foreground', 'button.foreground', null]],
  [
    'extensionButton.prominentHoverBackground',
    ['button.hoverBackground', 'button.hoverBackground', null],
  ],
  ['extensionIcon.starForeground', ['#DF6100', '#FF8E00', '#FF8E00']],
  [
    'ports.iconRunningProcessForeground',
    [
      'statusBarItem.remoteBackground',
      'statusBarItem.remoteBackground',
      'statusBarItem.remoteBackground',
    ],
  ],
  ['settings.headerForeground', ['#444444', '#e7e7e7', '#ffffff']],
  ['settings.modifiedItemIndicator', ['#66afe0ff', '#0c7d9dff', '#00497aff']],
  [
    'settings.dropdownBackground',
    ['dropdown.background', 'dropdown.background', 'dropdown.background'],
  ],
  [
    'settings.dropdownForeground',
    ['dropdown.foreground', 'dropdown.foreground', 'dropdown.foreground'],
  ],
  ['settings.dropdownBorder', ['dropdown.border', 'dropdown.border', 'dropdown.border']],
  [
    'settings.dropdownListBorder',
    ['editorWidget.border', 'editorWidget.border', 'editorWidget.border'],
  ],
  [
    'settings.checkboxBackground',
    ['checkbox.background', 'checkbox.background', 'checkbox.background'],
  ],
  [
    'settings.checkboxForeground',
    ['checkbox.foreground', 'checkbox.foreground', 'checkbox.foreground'],
  ],
  ['settings.checkboxBorder', ['checkbox.border', 'checkbox.border', 'checkbox.border']],
  ['settings.textInputBackground', ['input.background', 'input.background', 'input.background']],
  ['settings.textInputForeground', ['input.foreground', 'input.foreground', 'input.foreground']],
  ['settings.textInputBorder', ['input.border', 'input.border', 'input.border']],
  ['settings.numberInputBackground', ['input.background', 'input.background', 'input.background']],
  ['settings.numberInputForeground', ['input.foreground', 'input.foreground', 'input.foreground']],
  ['settings.numberInputBorder', ['input.border', 'input.border', 'input.border']],
  [
    'settings.focusedRowBackground',
    [{ op: 2, value: 'list.focusBackground', factor: 0.4 }, '#80808024', null],
  ],
  [
    'notebook.rowHoverBackground',
    [
      { op: 2, value: 'settings.focusedRowBackground', factor: 0.7 },
      { op: 2, value: 'settings.focusedRowBackground', factor: 0.5 },
      null,
    ],
  ],
  ['notebook.focusedRowBorder', ['#0000001f', '#ffffff1f', 'focusBorder']],
  ['peekViewTitle.background', ['#FFFFFF', '#1E1E1E', '#0C141F']],
  ['peekViewTitleLabel.foreground', ['#333333', '#FFFFFF', '#FFFFFF']],
  ['peekViewTitleDescription.foreground', ['#616161e6', '#ccccccb3', '#FFFFFF99']],
  ['peekView.border', ['#007acc', '#007acc', 'contrastBorder']],
  ['peekViewResult.background', ['#F3F3F3', '#252526', '#000000ff']],
  ['peekViewResult.lineForeground', ['#646465', '#bbbbbb', '#ffffffff']],
  ['peekViewResult.fileForeground', ['#1E1E1E', '#ffffffff', '#ffffffff']],
  ['peekViewResult.selectionBackground', ['#3399ff33', '#3399ff33', null]],
  ['peekViewResult.selectionForeground', ['#6C6C6C', '#ffffffff', '#ffffffff']],
  ['peekViewEditor.background', ['#F2F8FC', '#001F33', '#000000ff']],
  [
    'peekViewEditorGutter.background',
    ['peekViewEditor.background', 'peekViewEditor.background', 'peekViewEditor.background'],
  ],
  ['peekViewResult.matchHighlightBackground', ['#ea5c004d', '#ea5c004d', null]],
  ['peekViewEditor.matchHighlightBackground', ['#f5d802de', '#ff8f0099', null]],
  ['peekViewEditor.matchHighlightBorder', [null, null, 'contrastActiveBorder']],
  ['editorGutter.modifiedBackground', ['#66afe0ff', '#0c7d9dff', '#009bf9ff']],
  ['editorGutter.addedBackground', ['#81b88bff', '#587c0cff', '#33ab4eff']],
  ['editorGutter.deletedBackground', ['#ca4b51ff', '#94151bff', '#fc5d6dff']],
  ['minimapGutter.modifiedBackground', ['#66afe0ff', '#0c7d9dff', '#009bf9ff']],
  ['minimapGutter.addedBackground', ['#81b88bff', '#587c0cff', '#33ab4eff']],
  ['minimapGutter.deletedBackground', ['#ca4b51ff', '#94151bff', '#fc5d6dff']],
  [
    'editorOverviewRuler.modifiedForeground',
    [
      { op: 2, value: 'editorGutter.modifiedBackground', factor: 0.6 },
      { op: 2, value: 'editorGutter.modifiedBackground', factor: 0.6 },
      { op: 2, value: 'editorGutter.modifiedBackground', factor: 0.6 },
    ],
  ],
  [
    'editorOverviewRuler.addedForeground',
    [
      { op: 2, value: 'editorGutter.addedBackground', factor: 0.6 },
      { op: 2, value: 'editorGutter.addedBackground', factor: 0.6 },
      { op: 2, value: 'editorGutter.addedBackground', factor: 0.6 },
    ],
  ],
  [
    'editorOverviewRuler.deletedForeground',
    [
      { op: 2, value: 'editorGutter.deletedBackground', factor: 0.6 },
      { op: 2, value: 'editorGutter.deletedBackground', factor: 0.6 },
      { op: 2, value: 'editorGutter.deletedBackground', factor: 0.6 },
    ],
  ],
  [
    'editorMarkerNavigationError.background',
    [
      { op: 3, values: ['editorError.foreground', 'editorError.border'] },
      { op: 3, values: ['editorError.foreground', 'editorError.border'] },
      { op: 3, values: ['editorError.foreground', 'editorError.border'] },
    ],
  ],
  [
    'editorMarkerNavigationWarning.background',
    [
      { op: 3, values: ['editorWarning.foreground', 'editorWarning.border'] },
      { op: 3, values: ['editorWarning.foreground', 'editorWarning.border'] },
      { op: 3, values: ['editorWarning.foreground', 'editorWarning.border'] },
    ],
  ],
  [
    'editorMarkerNavigationInfo.background',
    [
      { op: 3, values: ['editorInfo.foreground', 'editorInfo.border'] },
      { op: 3, values: ['editorInfo.foreground', 'editorInfo.border'] },
      { op: 3, values: ['editorInfo.foreground', 'editorInfo.border'] },
    ],
  ],
  ['editorMarkerNavigation.background', ['#ffffffff', '#2D2D30', '#0C141F']],
  [
    'editorSuggestWidget.background',
    ['editorWidget.background', 'editorWidget.background', 'editorWidget.background'],
  ],
  [
    'editorSuggestWidget.border',
    ['editorWidget.border', 'editorWidget.border', 'editorWidget.border'],
  ],
  [
    'editorSuggestWidget.foreground',
    ['editor.foreground', 'editor.foreground', 'editor.foreground'],
  ],
  [
    'editorSuggestWidget.selectedForeground',
    [
      'quickInputList.focusForeground',
      'quickInputList.focusForeground',
      'quickInputList.focusForeground',
    ],
  ],
  [
    'editorSuggestWidget.selectedBackground',
    [
      'quickInputList.focusBackground',
      'quickInputList.focusBackground',
      'quickInputList.focusBackground',
    ],
  ],
  [
    'editorSuggestWidget.highlightForeground',
    ['list.highlightForeground', 'list.highlightForeground', 'list.highlightForeground'],
  ],
  [
    'editorSuggestWidget.focusHighlightForeground',
    [
      'list.focusHighlightForeground',
      'list.focusHighlightForeground',
      'list.focusHighlightForeground',
    ],
  ],
  ['debugIcon.breakpointForeground', ['#E51400', '#E51400', '#E51400']],
  ['debugIcon.breakpointDisabledForeground', ['#848484', '#848484', '#848484']],
  ['debugIcon.breakpointUnverifiedForeground', ['#848484', '#848484', '#848484']],
  ['debugIcon.breakpointCurrentStackframeForeground', ['#BE8700', '#FFCC00', '#FFCC00']],
  ['debugIcon.breakpointStackframeForeground', ['#89D185', '#89D185', '#89D185']],
  ['editor.inlineValuesForeground', ['#00000080', '#ffffff80', '#ffffff80']],
  ['editor.inlineValuesBackground', ['#ffc80033', '#ffc80033', '#ffc80033']],
  ['debugTokenExpression.name', ['#9b46b0', '#c586c0', 'foreground']],
  ['debugTokenExpression.value', ['#6c6c6ccc', '#cccccc99', 'foreground']],
  ['debugTokenExpression.string', ['#a31515', '#ce9178', '#f48771']],
  ['debugTokenExpression.boolean', ['#0000ff', '#4e94ce', '#75bdfe']],
  ['debugTokenExpression.number', ['#098658', '#b5cea8', '#89d185']],
  ['debugTokenExpression.error', ['#e51400', '#f48771', '#f48771']],
  ['debugView.exceptionLabelForeground', ['#FFF', 'foreground', 'foreground']],
  ['debugView.exceptionLabelBackground', ['#A31515', '#6C2022', '#6C2022']],
  ['debugView.stateLabelForeground', ['foreground', 'foreground', 'foreground']],
  ['debugView.stateLabelBackground', ['#88888844', '#88888844', '#88888844']],
  ['debugView.valueChangedHighlight', ['#569CD6', '#569CD6', '#569CD6']],
  ['debugConsole.infoForeground', ['editorInfo.foreground', 'editorInfo.foreground', 'foreground']],
  [
    'debugConsole.warningForeground',
    ['editorWarning.foreground', 'editorWarning.foreground', '#008000'],
  ],
  ['debugConsole.errorForeground', ['errorForeground', 'errorForeground', 'errorForeground']],
  ['debugConsole.sourceForeground', ['foreground', 'foreground', 'foreground']],
  ['debugConsoleInputIcon.foreground', ['foreground', 'foreground', 'foreground']],
  ['debugIcon.pauseForeground', ['#007ACC', '#75BEFF', '#75BEFF']],
  ['debugIcon.stopForeground', ['#A1260D', '#F48771', '#F48771']],
  ['debugIcon.disconnectForeground', ['#A1260D', '#F48771', '#F48771']],
  ['debugIcon.restartForeground', ['#388A34', '#89D185', '#89D185']],
  ['debugIcon.stepOverForeground', ['#007ACC', '#75BEFF', '#75BEFF']],
  ['debugIcon.stepIntoForeground', ['#007ACC', '#75BEFF', '#75BEFF']],
  ['debugIcon.stepOutForeground', ['#007ACC', '#75BEFF', '#75BEFF']],
  ['debugIcon.continueForeground', ['#007ACC', '#75BEFF', '#75BEFF']],
  ['debugIcon.stepBackForeground', ['#007ACC', '#75BEFF', '#75BEFF']],
  ['walkThrough.embeddedEditorBackground', [null, null, null]],
  ['scm.providerBorder', ['#C8C8C8', '#454545', 'contrastBorder']],
  ['searchEditor.textInputBorder', ['input.border', 'input.border', 'input.border']],
  [
    'notebook.cellBorderColor',
    [
      { op: 2, value: 'list.inactiveSelectionBackground', factor: 1 },
      { op: 2, value: 'list.inactiveSelectionBackground', factor: 1 },
      'panel.border',
    ],
  ],
  ['notebook.focusedEditorBorder', ['focusBorder', 'focusBorder', 'focusBorder']],
  [
    'notebookStatusSuccessIcon.foreground',
    ['debugIcon.startForeground', 'debugIcon.startForeground', 'debugIcon.startForeground'],
  ],
  ['notebookStatusErrorIcon.foreground', ['errorForeground', 'errorForeground', 'errorForeground']],
  ['notebookStatusRunningIcon.foreground', ['foreground', 'foreground', 'foreground']],
  [
    'notebook.outputContainerBackgroundColor',
    ['notebook.cellBorderColor', 'notebook.cellBorderColor', null],
  ],
  ['notebook.cellToolbarSeparator', ['#80808059', '#80808059', 'contrastBorder']],
  ['notebook.focusedCellBackground', [null, null, null]],
  [
    'notebook.selectedCellBackground',
    ['list.inactiveSelectionBackground', 'list.inactiveSelectionBackground', null],
  ],
  [
    'notebook.cellHoverBackground',
    [
      { op: 2, value: 'notebook.focusedCellBackground', factor: 0.7 },
      { op: 2, value: 'notebook.focusedCellBackground', factor: 0.5 },
      null,
    ],
  ],
  [
    'notebook.selectedCellBorder',
    ['notebook.cellBorderColor', 'notebook.cellBorderColor', 'contrastBorder'],
  ],
  ['notebook.inactiveSelectedCellBorder', [null, null, 'focusBorder']],
  ['notebook.focusedCellBorder', ['focusBorder', 'focusBorder', 'focusBorder']],
  [
    'notebook.inactiveFocusedCellBorder',
    ['notebook.cellBorderColor', 'notebook.cellBorderColor', 'notebook.cellBorderColor'],
  ],
  ['notebook.cellStatusBarItemHoverBackground', ['#00000014', '#ffffff26', '#ffffff26']],
  ['notebook.cellInsertionIndicator', ['focusBorder', 'focusBorder', 'focusBorder']],
  [
    'notebookScrollbarSlider.background',
    ['scrollbarSlider.background', 'scrollbarSlider.background', 'scrollbarSlider.background'],
  ],
  [
    'notebookScrollbarSlider.hoverBackground',
    [
      'scrollbarSlider.hoverBackground',
      'scrollbarSlider.hoverBackground',
      'scrollbarSlider.hoverBackground',
    ],
  ],
  [
    'notebookScrollbarSlider.activeBackground',
    [
      'scrollbarSlider.activeBackground',
      'scrollbarSlider.activeBackground',
      'scrollbarSlider.activeBackground',
    ],
  ],
  ['notebook.symbolHighlightBackground', ['#fdff0033', '#ffffff0b', null]],
  ['notebook.cellEditorBackground', [null, null, null]],
  ['terminal.ansiBlack', ['#000000', '#000000', '#000000']],
  ['terminal.ansiRed', ['#cd3131', '#cd3131', '#cd0000']],
  ['terminal.ansiGreen', ['#00BC00', '#0DBC79', '#00cd00']],
  ['terminal.ansiYellow', ['#949800', '#e5e510', '#cdcd00']],
  ['terminal.ansiBlue', ['#0451a5', '#2472c8', '#0000ee']],
  ['terminal.ansiMagenta', ['#bc05bc', '#bc3fbc', '#cd00cd']],
  ['terminal.ansiCyan', ['#0598bc', '#11a8cd', '#00cdcd']],
  ['terminal.ansiWhite', ['#555555', '#e5e5e5', '#e5e5e5']],
  ['terminal.ansiBrightBlack', ['#666666', '#666666', '#7f7f7f']],
  ['terminal.ansiBrightRed', ['#cd3131', '#f14c4c', '#ff0000']],
  ['terminal.ansiBrightGreen', ['#14CE14', '#23d18b', '#00ff00']],
  ['terminal.ansiBrightYellow', ['#b5ba00', '#f5f543', '#ffff00']],
  ['terminal.ansiBrightBlue', ['#0451a5', '#3b8eea', '#5c5cff']],
  ['terminal.ansiBrightMagenta', ['#bc05bc', '#d670d6', '#ff00ff']],
  ['terminal.ansiBrightCyan', ['#0598bc', '#29b8db', '#00ffff']],
  ['terminal.ansiBrightWhite', ['#a5a5a5', '#e5e5e5', '#ffffff']],
]);
